gg_rct_3v3 = nil
gg_rct_TeleportDestLeft = nil
gg_rct_TeleportDestRight = nil
gg_rct_RuneRight = nil
gg_rct_RuneLeft = nil
gg_rct_Region_005 = nil
gg_rct_Teleport2DestLeft = nil
gg_rct_Teleport2DestRight = nil
gg_rct_Teleport2DestTopLeft = nil
gg_rct_Teleport2DestTopRight = nil
gg_trg_Untitled_Trigger_001 = nil
gg_trg_Untitled_Trigger_002 = nil
gg_unit_ncop_0013 = nil
gg_unit_ncop_0014 = nil
function InitGlobals()
end

function CreateBuildingsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    gg_unit_ncop_0013 = BlzCreateUnitWithSkin(p, FourCC("ncop"), 576.0, -448.0, 270.000, FourCC("ncop"))
    u = BlzCreateUnitWithSkin(p, FourCC("ncop"), -5120.0, 1024.0, 270.000, FourCC("ncop"))
end

function CreateUnitsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 1725.8, -390.8, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 1215.1, 2174.9, 268.517, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 2451.8, 404.3, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 507.0, 1407.3, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h000"), 2614.6, 1658.7, 180.477, FourCC("h000"))
    u = BlzCreateUnitWithSkin(p, FourCC("h000"), 334.4, 114.9, 0.970, FourCC("h000"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 301.0, -383.6, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 304.1, -568.1, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -4360.9, -6788.2, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -3835.3, -6949.5, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 302.1, -159.0, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 2648.2, 1916.4, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 2645.2, 2100.9, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 2646.2, 2325.5, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -3614.1, -6631.0, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -3526.1, -6880.1, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -5185.1, -6951.3, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -4957.5, -6667.5, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -4684.6, -6960.6, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -4094.5, -6636.8, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -3255.4, -6641.1, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -3306.5, -6913.3, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -2858.2, -6747.5, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -3036.0, -6889.5, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -2615.2, -6603.6, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -2347.9, -6867.7, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -2611.1, -6857.3, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -2148.0, -6659.8, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -1872.2, -6926.4, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -1920.4, -6747.5, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -1551.4, -6626.4, 35.904, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), -1627.4, -6921.6, 35.904, FourCC("hmtt"))
end

function CreateBuildingsForPlayer1()
    local p = Player(1)
    local u
    local unitID
    local t
    local life
    gg_unit_ncop_0014 = BlzCreateUnitWithSkin(p, FourCC("ncop"), 2368.0, 2240.0, 270.000, FourCC("ncop"))
    u = BlzCreateUnitWithSkin(p, FourCC("ncop"), -1536.0, 1024.0, 270.000, FourCC("ncop"))
end

function CreateBuildingsForPlayer22()
    local p = Player(22)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("e000"), 768.0, -320.0, 270.000, FourCC("e000"))
    SetUnitColor(u, ConvertPlayerColor(0))
end

function CreateBuildingsForPlayer23()
    local p = Player(23)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("e001"), 2176.0, 2112.0, 270.000, FourCC("e001"))
    SetUnitColor(u, ConvertPlayerColor(1))
end

function CreateNeutralPassiveBuildings()
    local p = Player(PLAYER_NEUTRAL_PASSIVE)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("nwgt"), 2496.0, 768.0, 270.000, FourCC("nwgt"))
    WaygateSetDestination(u, GetRectCenterX(gg_rct_TeleportDestRight), GetRectCenterY(gg_rct_TeleportDestRight))
    WaygateActivate(u, true)
    u = BlzCreateUnitWithSkin(p, FourCC("nwgt"), 448.0, 1024.0, 270.000, FourCC("nwgt"))
    WaygateSetDestination(u, GetRectCenterX(gg_rct_TeleportDestLeft), GetRectCenterY(gg_rct_TeleportDestLeft))
    WaygateActivate(u, true)
    u = BlzCreateUnitWithSkin(p, FourCC("nwgt"), -5696.0, -6784.0, 270.000, FourCC("nwgt"))
    WaygateSetDestination(u, GetRectCenterX(gg_rct_TeleportDestRight), GetRectCenterY(gg_rct_TeleportDestRight))
    WaygateActivate(u, true)
    u = BlzCreateUnitWithSkin(p, FourCC("nwgt"), -960.0, -6784.0, 270.000, FourCC("nwgt"))
    WaygateSetDestination(u, GetRectCenterX(gg_rct_TeleportDestLeft), GetRectCenterY(gg_rct_TeleportDestLeft))
    WaygateActivate(u, true)
    u = BlzCreateUnitWithSkin(p, FourCC("nwgt"), -5760.0, -64.0, 270.000, FourCC("nwgt"))
    WaygateSetDestination(u, GetRectCenterX(gg_rct_Teleport2DestLeft), GetRectCenterY(gg_rct_Teleport2DestLeft))
    WaygateActivate(u, true)
    u = BlzCreateUnitWithSkin(p, FourCC("nwgt"), -896.0, 2176.0, 270.000, FourCC("nwgt"))
    WaygateSetDestination(u, GetRectCenterX(gg_rct_Teleport2DestRight), GetRectCenterY(gg_rct_Teleport2DestRight))
    WaygateActivate(u, true)
end

function CreateNeutralPassive()
    local p = Player(PLAYER_NEUTRAL_PASSIVE)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), 1907.2, 905.0, 35.900, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), 1035.6, 872.3, 35.900, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), 2608.5, -576.6, 35.900, FourCC("hmtt"))
    u = BlzCreateUnitWithSkin(p, FourCC("hmtt"), 318.1, 2347.0, 35.900, FourCC("hmtt"))
end

function CreatePlayerBuildings()
    CreateBuildingsForPlayer0()
    CreateBuildingsForPlayer1()
    CreateBuildingsForPlayer22()
    CreateBuildingsForPlayer23()
end

function CreatePlayerUnits()
    CreateUnitsForPlayer0()
end

function CreateAllUnits()
    CreateNeutralPassiveBuildings()
    CreatePlayerBuildings()
    CreateNeutralPassive()
    CreatePlayerUnits()
end

function CreateRegions()
    local we
    gg_rct_3v3 = Rect(0.0, -864.0, 2944.0, 2720.0)
    gg_rct_TeleportDestLeft = Rect(2432.0, -544.0, 2592.0, -384.0)
    gg_rct_TeleportDestRight = Rect(352.0, 2176.0, 512.0, 2336.0)
    gg_rct_RuneRight = Rect(1824.0, 224.0, 1920.0, 320.0)
    gg_rct_RuneLeft = Rect(1024.0, 1472.0, 1120.0, 1568.0)
    gg_rct_Region_005 = Rect(-6432.0, -960.0, -320.0, 2752.0)
    gg_rct_Teleport2DestLeft = Rect(-5792.0, -6880.0, -5632.0, -6720.0)
    gg_rct_Teleport2DestRight = Rect(-1056.0, -6848.0, -896.0, -6688.0)
    gg_rct_Teleport2DestTopLeft = Rect(-5824.0, -160.0, -5664.0, 0.0)
    gg_rct_Teleport2DestTopRight = Rect(-992.0, 2080.0, -832.0, 2240.0)
end

function Trig_Untitled_Trigger_001_Actions()
    BlzSetUnitName(gg_unit_ncop_0013, "Red")
    BlzSetUnitName(gg_unit_ncop_0014, "Blue")
end

function InitTrig_Untitled_Trigger_001()
    gg_trg_Untitled_Trigger_001 = CreateTrigger()
    TriggerAddAction(gg_trg_Untitled_Trigger_001, Trig_Untitled_Trigger_001_Actions)
end

function Trig_Untitled_Trigger_002_Actions()
end

function InitTrig_Untitled_Trigger_002()
    gg_trg_Untitled_Trigger_002 = CreateTrigger()
    TriggerAddAction(gg_trg_Untitled_Trigger_002, Trig_Untitled_Trigger_002_Actions)
end

function InitCustomTriggers()
    InitTrig_Untitled_Trigger_001()
    InitTrig_Untitled_Trigger_002()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    ForcePlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), false)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(1), false)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(2), 2)
    ForcePlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(2), false)
    SetPlayerController(Player(2), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(3), 3)
    ForcePlayerStartLocation(Player(3), 3)
    SetPlayerColor(Player(3), ConvertPlayerColor(3))
    SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(3), false)
    SetPlayerController(Player(3), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(6), 4)
    ForcePlayerStartLocation(Player(6), 4)
    SetPlayerColor(Player(6), ConvertPlayerColor(6))
    SetPlayerRacePreference(Player(6), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(6), false)
    SetPlayerController(Player(6), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(7), 5)
    ForcePlayerStartLocation(Player(7), 5)
    SetPlayerColor(Player(7), ConvertPlayerColor(7))
    SetPlayerRacePreference(Player(7), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(7), false)
    SetPlayerController(Player(7), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(8), 6)
    ForcePlayerStartLocation(Player(8), 6)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(8), false)
    SetPlayerController(Player(8), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(9), 7)
    ForcePlayerStartLocation(Player(9), 7)
    SetPlayerColor(Player(9), ConvertPlayerColor(9))
    SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(9), false)
    SetPlayerController(Player(9), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(22), 8)
    SetPlayerColor(Player(22), ConvertPlayerColor(22))
    SetPlayerRacePreference(Player(22), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(22), false)
    SetPlayerController(Player(22), MAP_CONTROL_NEUTRAL)
    SetPlayerStartLocation(Player(23), 9)
    SetPlayerColor(Player(23), ConvertPlayerColor(23))
    SetPlayerRacePreference(Player(23), RACE_PREF_NIGHTELF)
    SetPlayerRaceSelectable(Player(23), false)
    SetPlayerController(Player(23), MAP_CONTROL_NEUTRAL)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(1), 0)
    SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(2), 0)
    SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(3), 0)
    SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(22), 0)
    SetPlayerState(Player(22), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(3), true)
    SetPlayerTeam(Player(6), 1)
    SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(7), 1)
    SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(8), 1)
    SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(9), 1)
    SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(23), 1)
    SetPlayerState(Player(23), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(9), true)
end

function InitAllyPriorities()
    SetStartLocPrioCount(0, 7)
    SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 2, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(1, 7)
    SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 2, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(2, 7)
    SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 2, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(3, 7)
    SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(4, 7)
    SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(5, 7)
    SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(6, 7)
    SetStartLocPrio(6, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(7, 7)
    SetStartLocPrio(7, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 6, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(8, 2)
    SetStartLocPrio(8, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 1, 9, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(8, 8)
    SetEnemyStartLocPrio(8, 0, 0, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(8, 1, 1, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(8, 2, 2, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(8, 3, 3, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(8, 4, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(8, 5, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(8, 6, 6, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(8, 7, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(9, 7)
    SetStartLocPrio(9, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 2, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(9, 3, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(9, 4, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(9, 5, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(9, 6, 8, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(9, 3)
    SetEnemyStartLocPrio(9, 0, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(9, 1, 6, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(9, 2, 7, MAP_LOC_PRIO_LOW)
end

function main()
    SetCameraBounds(-7424.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -7680.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -7424.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -7680.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCUnderground\\DNCUndergroundTerrain\\DNCUndergroundTerrain.mdl", "Environment\\DNC\\DNCUnderground\\DNCUndergroundUnit\\DNCUndergroundUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("DungeonDay")
    SetAmbientNightSound("DungeonNight")
    SetMapMusic("Music", true, 0)
    CreateRegions()
    CreateAllUnits()
    InitBlizzard()
    InitGlobals()
    InitCustomTriggers()
end

function config()
    SetMapName("TRIGSTR_001")
    SetMapDescription("TRIGSTR_003")
    SetPlayers(10)
    SetTeams(10)
    SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    DefineStartLocation(0, 4032.0, 3840.0)
    DefineStartLocation(1, 4032.0, 3840.0)
    DefineStartLocation(2, 4032.0, 3840.0)
    DefineStartLocation(3, 4032.0, 3840.0)
    DefineStartLocation(4, 4032.0, 3840.0)
    DefineStartLocation(5, 4032.0, 3840.0)
    DefineStartLocation(6, 4032.0, 3840.0)
    DefineStartLocation(7, 4032.0, 3840.0)
    DefineStartLocation(8, 4032.0, 3840.0)
    DefineStartLocation(9, 4032.0, 3840.0)
    InitCustomPlayerSlots()
    InitCustomTeams()
    InitAllyPriorities()
end

