gg_rct_Region_000 = nil
gg_trg_Untitled_Trigger_001 = nil
gg_trg_Untitled_Trigger_002 = nil
gg_unit_ncop_0013 = nil
gg_unit_ncop_0014 = nil
gg_trg_Untitled_Trigger_003 = nil
function InitGlobals()
end

function CreateBuildingsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    gg_unit_ncop_0013 = BlzCreateUnitWithSkin(p, FourCC("ncop"), 448.0, -448.0, 270.000, FourCC("ncop"))
end

function CreateUnitsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 1725.8, -390.8, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 1215.1, 2174.9, 268.517, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 2451.8, 404.3, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h001"), 507.0, 1407.3, 90.769, FourCC("h001"))
    u = BlzCreateUnitWithSkin(p, FourCC("h000"), 2614.6, 1658.7, 180.477, FourCC("h000"))
    u = BlzCreateUnitWithSkin(p, FourCC("h000"), 334.4, 114.9, 0.970, FourCC("h000"))
end

function CreateBuildingsForPlayer1()
    local p = Player(1)
    local u
    local unitID
    local t
    local life
    gg_unit_ncop_0014 = BlzCreateUnitWithSkin(p, FourCC("ncop"), 2496.0, 2240.0, 270.000, FourCC("ncop"))
end

function CreateBuildingsForPlayer22()
    local p = Player(22)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("e000"), 256.0, -256.0, 270.000, FourCC("e000"))
    SetUnitColor(u, ConvertPlayerColor(0))
end

function CreateBuildingsForPlayer23()
    local p = Player(23)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("e001"), 2688.0, 2432.0, 270.000, FourCC("e001"))
    SetUnitColor(u, ConvertPlayerColor(1))
end

function CreatePlayerBuildings()
    CreateBuildingsForPlayer0()
    CreateBuildingsForPlayer1()
    CreateBuildingsForPlayer22()
    CreateBuildingsForPlayer23()
end

function CreatePlayerUnits()
    CreateUnitsForPlayer0()
end

function CreateAllUnits()
    CreatePlayerBuildings()
    CreatePlayerUnits()
end

function CreateRegions()
    local we
    gg_rct_Region_000 = Rect(256.0, -640.0, 2688.0, 2432.0)
end

function Trig_Untitled_Trigger_001_Actions()
    BlzSetUnitName(gg_unit_ncop_0013, "Red")
    BlzSetUnitName(gg_unit_ncop_0014, "Blue")
end

function InitTrig_Untitled_Trigger_001()
    gg_trg_Untitled_Trigger_001 = CreateTrigger()
    TriggerAddAction(gg_trg_Untitled_Trigger_001, Trig_Untitled_Trigger_001_Actions)
end

function Trig_Untitled_Trigger_002_Actions()
end

function InitTrig_Untitled_Trigger_002()
    gg_trg_Untitled_Trigger_002 = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(gg_trg_Untitled_Trigger_002, EVENT_PLAYER_UNIT_SUMMON)
    TriggerAddAction(gg_trg_Untitled_Trigger_002, Trig_Untitled_Trigger_002_Actions)
end

function Trig_Untitled_Trigger_003_Func001C()
    return false
end

function Trig_Untitled_Trigger_003_Conditions()
    if (not Trig_Untitled_Trigger_003_Func001C()) then
        return false
    end
    return true
end

function Trig_Untitled_Trigger_003_Actions()
end

function InitTrig_Untitled_Trigger_003()
    gg_trg_Untitled_Trigger_003 = CreateTrigger()
    TriggerAddCondition(gg_trg_Untitled_Trigger_003, Condition(Trig_Untitled_Trigger_003_Conditions))
    TriggerAddAction(gg_trg_Untitled_Trigger_003, Trig_Untitled_Trigger_003_Actions)
end

function InitCustomTriggers()
    InitTrig_Untitled_Trigger_001()
    InitTrig_Untitled_Trigger_002()
    InitTrig_Untitled_Trigger_003()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    ForcePlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), false)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(1), false)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(2), 2)
    ForcePlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(2), false)
    SetPlayerController(Player(2), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(3), 3)
    ForcePlayerStartLocation(Player(3), 3)
    SetPlayerColor(Player(3), ConvertPlayerColor(3))
    SetPlayerRacePreference(Player(3), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(3), false)
    SetPlayerController(Player(3), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(4), 4)
    ForcePlayerStartLocation(Player(4), 4)
    SetPlayerColor(Player(4), ConvertPlayerColor(4))
    SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(4), false)
    SetPlayerController(Player(4), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(5), 5)
    ForcePlayerStartLocation(Player(5), 5)
    SetPlayerColor(Player(5), ConvertPlayerColor(5))
    SetPlayerRacePreference(Player(5), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(5), false)
    SetPlayerController(Player(5), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(6), 6)
    ForcePlayerStartLocation(Player(6), 6)
    SetPlayerColor(Player(6), ConvertPlayerColor(6))
    SetPlayerRacePreference(Player(6), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(6), false)
    SetPlayerController(Player(6), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(7), 7)
    ForcePlayerStartLocation(Player(7), 7)
    SetPlayerColor(Player(7), ConvertPlayerColor(7))
    SetPlayerRacePreference(Player(7), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(7), false)
    SetPlayerController(Player(7), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(8), 8)
    ForcePlayerStartLocation(Player(8), 8)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(8), false)
    SetPlayerController(Player(8), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(9), 9)
    ForcePlayerStartLocation(Player(9), 9)
    SetPlayerColor(Player(9), ConvertPlayerColor(9))
    SetPlayerRacePreference(Player(9), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(9), false)
    SetPlayerController(Player(9), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(10), 10)
    ForcePlayerStartLocation(Player(10), 10)
    SetPlayerColor(Player(10), ConvertPlayerColor(10))
    SetPlayerRacePreference(Player(10), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(10), false)
    SetPlayerController(Player(10), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(11), 11)
    ForcePlayerStartLocation(Player(11), 11)
    SetPlayerColor(Player(11), ConvertPlayerColor(11))
    SetPlayerRacePreference(Player(11), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(11), false)
    SetPlayerController(Player(11), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(22), 12)
    SetPlayerColor(Player(22), ConvertPlayerColor(22))
    SetPlayerRacePreference(Player(22), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(22), false)
    SetPlayerController(Player(22), MAP_CONTROL_NEUTRAL)
    SetPlayerStartLocation(Player(23), 13)
    SetPlayerColor(Player(23), ConvertPlayerColor(23))
    SetPlayerRacePreference(Player(23), RACE_PREF_NIGHTELF)
    SetPlayerRaceSelectable(Player(23), false)
    SetPlayerController(Player(23), MAP_CONTROL_NEUTRAL)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(1), 0)
    SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(2), 0)
    SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(3), 0)
    SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(4), 0)
    SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(5), 0)
    SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(22), 0)
    SetPlayerState(Player(22), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(22), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(22), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(22), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(22), Player(5), true)
    SetPlayerTeam(Player(6), 1)
    SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(7), 1)
    SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(8), 1)
    SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(9), 1)
    SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(10), 1)
    SetPlayerState(Player(10), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(11), 1)
    SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(23), 1)
    SetPlayerState(Player(23), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(11), true)
    SetPlayerAllianceStateAllyBJ(Player(10), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(11), Player(23), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(10), true)
    SetPlayerAllianceStateAllyBJ(Player(23), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(11), true)
    SetPlayerAllianceStateVisionBJ(Player(10), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(11), Player(23), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(10), true)
    SetPlayerAllianceStateVisionBJ(Player(23), Player(11), true)
end

function InitAllyPriorities()
    SetStartLocPrioCount(0, 11)
    SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 2, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(1, 11)
    SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 2, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(2, 11)
    SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 2, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(3, 11)
    SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(4, 11)
    SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(5, 11)
    SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(6, 11)
    SetStartLocPrio(6, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(7, 11)
    SetStartLocPrio(7, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 6, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(8, 11)
    SetStartLocPrio(8, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 6, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 7, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(9, 11)
    SetStartLocPrio(9, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 6, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 7, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 8, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 9, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(10, 11)
    SetStartLocPrio(10, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 6, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 7, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 8, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 9, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 10, 11, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(11, 11)
    SetStartLocPrio(11, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 6, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 7, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 8, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 9, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 10, 10, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(12, 4)
    SetStartLocPrio(12, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 2, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 3, 13, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrioCount(12, 12)
    SetEnemyStartLocPrio(12, 0, 0, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 1, 1, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 2, 2, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 3, 3, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(12, 4, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 5, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 6, 6, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 7, 7, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 8, 8, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 9, 9, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 10, 10, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 11, 11, MAP_LOC_PRIO_LOW)
    SetStartLocPrioCount(13, 10)
    SetStartLocPrio(13, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(13, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(13, 2, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 3, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 4, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 5, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 6, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 7, 10, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 8, 11, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(13, 9, 12, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(13, 6)
    SetEnemyStartLocPrio(13, 0, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 1, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 2, 7, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 3, 8, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 4, 9, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(13, 5, 10, MAP_LOC_PRIO_LOW)
end

function main()
    SetCameraBounds(-3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCDalaran\\DNCDalaranTerrain\\DNCDalaranTerrain.mdl", "Environment\\DNC\\DNCDalaran\\DNCDalaranUnit\\DNCDalaranUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("DalaranDay")
    SetAmbientNightSound("DalaranNight")
    SetMapMusic("Music", true, 0)
    CreateRegions()
    CreateAllUnits()
    InitBlizzard()
    InitGlobals()
    InitCustomTriggers()
end

function config()
    SetMapName("TRIGSTR_001")
    SetMapDescription("TRIGSTR_003")
    SetPlayers(14)
    SetTeams(14)
    SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    DefineStartLocation(0, 576.0, -448.0)
    DefineStartLocation(1, 576.0, -448.0)
    DefineStartLocation(2, 576.0, -448.0)
    DefineStartLocation(3, 576.0, -448.0)
    DefineStartLocation(4, 576.0, -448.0)
    DefineStartLocation(5, 576.0, -448.0)
    DefineStartLocation(6, 2304.0, 2176.0)
    DefineStartLocation(7, 2304.0, 2176.0)
    DefineStartLocation(8, 2304.0, 2176.0)
    DefineStartLocation(9, 2304.0, 2176.0)
    DefineStartLocation(10, 2304.0, 2176.0)
    DefineStartLocation(11, 2304.0, 2176.0)
    DefineStartLocation(12, -448.0, -3072.0)
    DefineStartLocation(13, 2240.0, -1472.0)
    InitCustomPlayerSlots()
    InitCustomTeams()
    InitAllyPriorities()
end

